<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div id="designer" class="block designer">
      <div class="content">
            <div class="designer-name">
                  <ul class="items">
                        <li><span><a href="#" class="action">Jonathan Simkhai</a></span></li>
                        <li><span><a href="#" class="action">Blazers</a></span></li>
                        <li><span><a href="#" class="action">Viscose</a></span></li>
                  </ul>
            </div>
      </div>
</div>