<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div id="editornote" class="block editor-note">
<div class="title"><strong><?= $block->escapeHtml(__('a note from the editor')) ?></strong></div>

<div class="content">
      <div class="editor-description">The Forte Lurex Linen Viscose Jacket in Mother of Pearl features lunar lavishness by night and by day: a blazer in a linen blend shot with lurex for a shimmering surface that shines like a star in the sky. </div>

      <div class="author-name"><span>By <a href="#" class="action">MINNA SHIM,</a> Fashion Editor</span></div>
</div>


</div>